image: Ubuntu1804 # образ для сборки

stack: node 12 # окружение

branches:
  only:
    - master # ветка git

cache: node_modules # кеширование

install:
  - npm install # команда установки зависимостей

build: off # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build # команда сборки

test_script:
  - npm run lint && npm run test # скрипт тестирования

environment: # переменные окружения
  SERVER_URL: https://ahj7-http-backend.herokuapp.com

deploy_script: # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name "Alexey Shishkin"
  - git config --global user.email %github_email%
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
